export const locationData: LocationType[] = [
  {
    id: 1,
    gateNumber: "A1",
    address1: "1234 Street",
    address2: "Near Tech Park",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    zipCode: "560001",
    status: false,
  },
  {
    id: 2,
    gateNumber: "B1",
    address1: "1234 Street",
    address2: "Near Tech Park",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    zipCode: "560001",
    status: true,
  },
  {
    id: 3,
    gateNumber: "C1",
    address1: "1234 Street",
    address2: "Near Tech Park",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    zipCode: "560001",
    status: true,
  },
  {
    id: 4,
    gateNumber: "D1",
    address1: "1234 Street",
    address2: "Near Tech Park",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    zipCode: "560001",
    status: false,
  },
  {
    id: 5,
    gateNumber: "E1",
    address1: "1234 Street",
    address2: "Near Tech Park",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    zipCode: "560001",
    status: false,
  },
]
